import { createHash } from 'node:crypto';
import path from 'node:path';
import type {
  IRBeanDefinition,
  IRControllerDefinition,
  IRRouteValidation,
  TokenRef,
} from './ir.js';
import type { CodegenContribution } from './options.js';

/** Info about an auto-generated InjectionToken. */
interface TokenInfo {
  tokenName: string;
  typeAnnotation: string | undefined;
}

/** Options for code generation. */
export interface CodegenOptions {
  /** Absolute path of the output file (used for computing relative imports). */
  outputPath: string;
  /** Transformer version string (e.g. '0.1.0'). Embedded in the header comment. */
  version?: string;
  /** Pre-computed IR hash. When provided, skips recomputation inside generateCode(). */
  hash?: string;
}

/**
 * Compute a SHA-256 hash of all codegen inputs.
 * Used to skip codegen + file write when the DI graph hasn't changed.
 */
export function computeIRHash(
  beans: IRBeanDefinition[],
  options: CodegenOptions,
  contributions?: CodegenContribution[],
  controllers?: IRControllerDefinition[],
): string {
  const json = JSON.stringify(
    {
      beans,
      options,
      contributions: contributions ?? [],
      controllers: controllers ?? [],
    },
    mapReplacer,
  );
  return createHash('sha256').update(json).digest('hex').slice(0, 16);
}

/** JSON replacer that serializes Map instances as sorted [key, value] arrays. */
function mapReplacer(_key: string, value: unknown): unknown {
  if (value instanceof Map) {
    return [...value.entries()].sort((a, b) => a[0].localeCompare(b[0]));
  }
  return value;
}

/** Extract the IR hash from a generated file's header line, or undefined if not found. */
export function extractIRHash(fileContent: string): string | undefined {
  const match = fileContent.match(/^\/\/ .+— hash:([a-f0-9]+)/);
  return match?.[1];
}

/**
 * Generate the AppContext.generated.ts source from topologically sorted beans.
 */
export function generateCode(
  beans: IRBeanDefinition[],
  options: CodegenOptions,
  contributions?: CodegenContribution[],
  controllers?: IRControllerDefinition[],
): string {
  const outputDir = path.dirname(options.outputPath);
  const importCache = new Map<string, string>();
  const relativeImport = (absolutePath: string): string => {
    const cached = importCache.get(absolutePath);
    if (cached) return cached;
    const result = computeRelativeImport(outputDir, absolutePath);
    importCache.set(absolutePath, result);
    return result;
  };
  const lines: string[] = [];

  // Generate EmbeddedServer when controllers exist (implies @goodie-ts/hono is installed)
  const needsEmbeddedServer = (controllers ?? []).length > 0;

  // Check if any bean uses @Value
  const hasValueFields = beans.some(
    (b) =>
      b.metadata.valueFields &&
      (b.metadata.valueFields as unknown[]).length > 0,
  );

  // Header
  const versionTag = options.version ? ` v${options.version}` : '';
  const hash =
    options.hash ?? computeIRHash(beans, options, contributions, controllers);
  lines.push(
    `// AppContext.generated.ts — DO NOT EDIT (generated by @goodie-ts/transformer${versionTag} — hash:${hash})`,
  );
  lines.push("import { ApplicationContext, Goodie } from '@goodie-ts/core'");
  lines.push("import type { BeanDefinition } from '@goodie-ts/core'");

  // Collect all imports in a single pass
  const {
    classImports,
    injectionTokens,
    typeOnlyImports,
    interceptorDepsPerBean,
  } = collectAllImports(beans, outputDir, relativeImport);

  // If @Value is used, add the config token
  const needsInjectionToken = injectionTokens.length > 0 || hasValueFields;
  if (needsInjectionToken) {
    lines.push("import { InjectionToken } from '@goodie-ts/core'");
  }

  // Build collision-safe tokenName → varName mapping
  const tokenVarNameMap = buildTokenVarNameMap(injectionTokens);
  const resolveTokenRef = (ref: TokenRef): string => {
    if (ref.kind === 'class') return ref.className;
    return tokenVarNameMap.get(ref.tokenName) ?? tokenVarName(ref.tokenName);
  };

  // Class imports — group by import path to produce single import lines
  const importsByPath = new Map<string, string[]>();
  for (const [className, importPath] of classImports) {
    const relativePath = relativeImport(importPath);
    const existing = importsByPath.get(relativePath) ?? [];
    if (!existing.includes(className)) {
      existing.push(className);
    }
    importsByPath.set(relativePath, existing);
  }
  for (const [relativePath, classNames] of importsByPath) {
    lines.push(
      `import { ${classNames.sort().join(', ')} } from '${relativePath}'`,
    );
  }

  // EmbeddedServer imports (when controllers exist)
  if (needsEmbeddedServer) {
    lines.push("import { Hono } from 'hono'");
    lines.push("import { EmbeddedServer } from '@goodie-ts/hono'");

    // Validation imports (when any route has @Validate)
    const allRoutes = (controllers ?? []).flatMap((c) => c.routes);
    const hasValidation = allRoutes.some(
      (r) => r.validation && r.validation.length > 0,
    );
    if (hasValidation) {
      lines.push("import { zValidator } from '@hono/zod-validator'");
      // Collect unique schema imports
      const schemaImports = collectSchemaImports(controllers ?? [], outputDir);
      for (const [schemaRef, importSpec] of schemaImports) {
        lines.push(`import { ${schemaRef} } from '${importSpec}'`);
      }
    }
  }

  // Type-only imports for types referenced in token generics
  for (const [typeName, importSpec] of typeOnlyImports) {
    lines.push(`import type { ${typeName} } from '${importSpec}'`);
  }

  // Plugin contribution imports (deduplicated against class imports and each other)
  if (contributions && contributions.length > 0) {
    // Track already-imported symbols per path to avoid duplicates
    const importedSymbols = new Set<string>();
    for (const [className, importPath] of classImports) {
      const relativePath = relativeImport(importPath);
      importedSymbols.add(`${className}:${relativePath}`);
    }

    for (const contrib of contributions) {
      if (contrib.imports) {
        for (const imp of contrib.imports) {
          // Parse "import { A, B } from 'path'" to extract symbols and path
          const match = imp.match(
            /^import\s+(?:type\s+)?{\s*(.+?)\s*}\s+from\s+['"](.+?)['"]/,
          );
          if (!match) {
            // Non-standard import line — add if not already present
            lines.push(imp);
            continue;
          }
          const symbols = match[1].split(',').map((s) => s.trim());
          const importPath = match[2];
          const newSymbols = symbols.filter(
            (s) => !importedSymbols.has(`${s}:${importPath}`),
          );
          for (const s of newSymbols) {
            importedSymbols.add(`${s}:${importPath}`);
          }
          if (newSymbols.length > 0) {
            const isTypeImport = imp.startsWith('import type');
            const keyword = isTypeImport ? 'import type' : 'import';
            lines.push(
              `${keyword} { ${newSymbols.join(', ')} } from '${importPath}'`,
            );
          }
        }
      }
    }
  }

  lines.push('');

  // Config token (if @Value is used)
  // Reserved name — graph-builder validates no user bean collides with '__Goodie_Config'
  if (hasValueFields) {
    lines.push(
      "export const __Goodie_Config = new InjectionToken<Record<string, unknown>>('__Goodie_Config')",
    );
    lines.push('');
  }

  // InjectionToken declarations (exported + typed)
  for (const token of injectionTokens) {
    const varName = tokenVarNameMap.get(token.tokenName)!;
    const typeParam = token.typeAnnotation ?? 'unknown';
    lines.push(
      `export const ${varName} = new InjectionToken<${typeParam}>('${token.tokenName}')`,
    );
  }

  if (injectionTokens.length > 0) {
    lines.push('');
  }

  // Bean definitions array
  if (hasValueFields) {
    lines.push(
      'export function buildDefinitions(config?: Record<string, unknown>): BeanDefinition[] {',
    );
    lines.push('  return [');
    // Config bean definition
    lines.push('    {');
    lines.push('      token: __Goodie_Config,');
    lines.push("      scope: 'singleton',");
    lines.push('      dependencies: [],');
    lines.push(
      '      factory: () => ({ ...process.env, ...config } as Record<string, unknown>),',
    );
    lines.push('      eager: false,');
    lines.push('      metadata: {},');
    lines.push('    },');
  } else {
    lines.push('const definitions: BeanDefinition[] = [');
  }

  for (const bean of beans) {
    lines.push('  {');
    lines.push(`    token: ${resolveTokenRef(bean.tokenRef)},`);
    lines.push(`    scope: '${bean.scope}',`);
    lines.push(
      `    dependencies: ${depsToCode(bean, resolveTokenRef, hasValueFields, interceptorDepsPerBean)},`,
    );
    lines.push(`    factory: ${bean.customFactory ?? factoryToCode(bean, interceptorDepsPerBean)},`);
    lines.push(`    eager: ${bean.eager},`);
    lines.push(`    metadata: ${metadataToCode(bean.metadata)},`);
    if (bean.baseTokenRefs && bean.baseTokenRefs.length > 0) {
      const baseTokensList = bean.baseTokenRefs
        .map((ref) => ref.className)
        .join(', ');
      lines.push(`    baseTokens: [${baseTokensList}],`);
    }
    lines.push('  },');
  }

  // EmbeddedServer bean definition (when controllers with routes exist)
  if (needsEmbeddedServer) {
    lines.push(...generateEmbeddedServerBeanDef(controllers!));
  }

  if (hasValueFields) {
    lines.push('  ]');
    lines.push('}');
    lines.push('');
    lines.push('const definitions = buildDefinitions()');
  } else {
    lines.push(']');
  }
  lines.push('');

  // createContext function
  if (hasValueFields) {
    lines.push(
      'export async function createContext(config?: Record<string, unknown>): Promise<ApplicationContext> {',
    );
    lines.push(
      '  return ApplicationContext.create(buildDefinitions(config), { preSorted: true })',
    );
    lines.push('}');
  } else {
    lines.push(
      'export async function createContext(): Promise<ApplicationContext> {',
    );
    lines.push(
      '  return ApplicationContext.create(definitions, { preSorted: true })',
    );
    lines.push('}');
  }
  lines.push('');
  lines.push('export { definitions }');
  lines.push('');

  if (hasValueFields) {
    lines.push('export function createApp(config?: Record<string, unknown>) {');
    lines.push('  return Goodie.build(buildDefinitions(config))');
    lines.push('}');
    lines.push('');
    lines.push('export const app = createApp()');
  } else {
    lines.push('export const app = Goodie.build(definitions)');
  }
  lines.push('');

  // Plugin contribution code
  if (contributions && contributions.length > 0) {
    const codeLines: string[] = [];
    for (const contrib of contributions) {
      if (contrib.code) codeLines.push(...contrib.code);
    }
    if (codeLines.length > 0) {
      lines.push('// Plugin contributions');
      lines.push(...codeLines);
      lines.push('');
    }
  }

  // Generate startServer() when controllers exist
  if (needsEmbeddedServer) {
    lines.push(
      'export async function startServer(options?: { port?: number }) {',
    );
    lines.push('  const ctx = await app.start()');
    lines.push('  ctx.get(EmbeddedServer).listen(options)');
    lines.push('  return ctx');
    lines.push('}');
    lines.push('');
  }

  return lines.join('\n');
}

/** Result of collecting all import-related data in a single pass. */
interface CollectedImports {
  classImports: Map<string, string>;
  injectionTokens: TokenInfo[];
  typeOnlyImports: Map<string, string>;
  interceptorDepsPerBean: Map<
    IRBeanDefinition,
    Map<string, InterceptorRefMeta>
  >;
}

/**
 * Collect all import-related data in a single iteration over beans:
 * class imports, injection tokens, type-only imports, and per-bean interceptor deps.
 */
function collectAllImports(
  beans: IRBeanDefinition[],
  outputDir: string,
  relativeImport?: (absolutePath: string) => string,
): CollectedImports {
  const classImports = new Map<string, string>();
  const tokensSeen = new Map<string, TokenInfo>();
  const rawTypeImports: Array<[string, string]> = [];
  const interceptorDepsPerBean = new Map<
    IRBeanDefinition,
    Map<string, InterceptorRefMeta>
  >();

  for (const bean of beans) {
    // Class imports
    addClassImport(classImports, bean.tokenRef);
    for (const dep of bean.constructorDeps) {
      addClassImport(classImports, dep.tokenRef);
    }
    for (const field of bean.fieldDeps) {
      addClassImport(classImports, field.tokenRef);
    }
    if (bean.providesSource) {
      addClassImport(classImports, bean.providesSource.moduleTokenRef);
    }
    if (bean.baseTokenRefs) {
      for (const ref of bean.baseTokenRefs) {
        addClassImport(classImports, ref);
      }
    }

    // Interceptor deps (computed once per bean, cached for reuse)
    const interceptorDeps = collectInterceptorDeps(bean);
    if (interceptorDeps.size > 0) {
      interceptorDepsPerBean.set(bean, interceptorDeps);
      for (const ref of interceptorDeps.values()) {
        if (ref.importPath) {
          classImports.set(ref.className, ref.importPath);
        }
      }
    }

    // Injection tokens
    addToken(tokensSeen, bean.tokenRef);
    for (const dep of bean.constructorDeps) {
      addToken(tokensSeen, dep.tokenRef);
    }
    for (const field of bean.fieldDeps) {
      addToken(tokensSeen, field.tokenRef);
    }

    // Type imports (collected raw, filtered later)
    addRawTypeImports(rawTypeImports, bean.tokenRef);
    for (const dep of bean.constructorDeps) {
      addRawTypeImports(rawTypeImports, dep.tokenRef);
    }
    for (const field of bean.fieldDeps) {
      addRawTypeImports(rawTypeImports, field.tokenRef);
    }
  }

  // Filter type imports against class imports (and deduplicate)
  const typeOnlyImports = new Map<string, string>();
  for (const [typeName, absolutePath] of rawTypeImports) {
    if (classImports.has(typeName)) continue;
    if (typeOnlyImports.has(typeName)) continue;
    typeOnlyImports.set(
      typeName,
      relativeImport
        ? relativeImport(absolutePath)
        : computeRelativeImport(outputDir, absolutePath),
    );
  }

  return {
    classImports,
    injectionTokens: [...tokensSeen.values()],
    typeOnlyImports,
    interceptorDepsPerBean,
  };
}

function addClassImport(imports: Map<string, string>, ref: TokenRef): void {
  if (ref.kind === 'class') {
    imports.set(ref.className, ref.importPath);
  }
}

function addToken(seen: Map<string, TokenInfo>, ref: TokenRef): void {
  if (ref.kind !== 'injection-token') return;
  if (seen.has(ref.tokenName)) return;
  seen.set(ref.tokenName, {
    tokenName: ref.tokenName,
    typeAnnotation: ref.typeAnnotation,
  });
}

function addRawTypeImports(out: Array<[string, string]>, ref: TokenRef): void {
  if (ref.kind !== 'injection-token') return;
  if (!ref.typeImports) return;
  for (const [typeName, absolutePath] of ref.typeImports) {
    out.push([typeName, absolutePath]);
  }
}

/**
 * Build a Map<tokenName, uniqueVarName> with collision detection.
 * When two different tokenNames produce the same varName, append _2, _3, etc.
 */
function buildTokenVarNameMap(tokens: TokenInfo[]): Map<string, string> {
  const result = new Map<string, string>();
  // Track varName → how many times it's been assigned (for suffix generation)
  const varNameCounts = new Map<string, number>();

  for (const token of tokens) {
    const baseVarName = tokenVarName(token.tokenName);
    const count = varNameCounts.get(baseVarName) ?? 0;

    if (count === 0) {
      result.set(token.tokenName, baseVarName);
    } else {
      result.set(token.tokenName, `${baseVarName}_${count + 1}`);
    }
    varNameCounts.set(baseVarName, count + 1);
  }

  return result;
}

/**
 * Generate the exported variable name for a token in Pascal_Snake_Case.
 * E.g. 'Repository<User>' → 'Repository_User_Token'
 *      'appName'           → 'App_Name_Token'
 *      'dbUrl'             → 'Db_Url_Token'
 *      'port'              → 'Port_Token'
 */
function tokenVarName(tokenName: string): string {
  // 1. Replace generic chars with underscores
  const sanitized = tokenName.replace(/[<>, ]/g, '_');

  // 2. Split on underscores, filter empty segments
  const segments = sanitized.split('_').filter(Boolean);

  // 3. Split camelCase within each segment, capitalize each word
  const words = segments.flatMap((seg) =>
    seg
      .replace(/([a-z])([A-Z])/g, '$1_$2')
      .split('_')
      .map((w) => w.charAt(0).toUpperCase() + w.slice(1)),
  );

  return [...words, 'Token'].join('_');
}

/** Metadata shape for intercepted methods (from AOP plugin or other plugins). */
interface InterceptorRefMeta {
  className: string;
  importPath: string;
  adviceType: 'around' | 'before' | 'after';
  order: number;
  metadata?: Record<string, unknown>;
}
interface InterceptedMethodMeta {
  methodName: string;
  interceptors: InterceptorRefMeta[];
}

/** Collect unique interceptor class tokens from bean metadata, in stable order. */
function collectInterceptorDeps(
  bean: IRBeanDefinition,
): Map<string, InterceptorRefMeta> {
  const interceptedMethods = bean.metadata.interceptedMethods as
    | InterceptedMethodMeta[]
    | undefined;
  if (!interceptedMethods || interceptedMethods.length === 0) return new Map();

  const unique = new Map<string, InterceptorRefMeta>();
  for (const method of interceptedMethods) {
    for (const ref of method.interceptors) {
      const key = `${ref.importPath}:${ref.className}`;
      if (!unique.has(key)) {
        unique.set(key, ref);
      }
    }
  }
  return unique;
}

/** Convert all dependencies of a bean (constructor + field + interceptor) to code. */
function depsToCode(
  bean: IRBeanDefinition,
  resolveTokenRef: (ref: TokenRef) => string,
  hasValueFields: boolean,
  cachedInterceptorDeps: Map<IRBeanDefinition, Map<string, InterceptorRefMeta>>,
): string {
  const allDeps = [
    ...bean.constructorDeps.map((d) => ({
      token: resolveTokenRef(d.tokenRef),
      optional: d.optional,
      collection: d.collection,
    })),
    ...bean.fieldDeps.map((f) => ({
      token: resolveTokenRef(f.tokenRef),
      optional: f.optional,
      collection: false,
    })),
  ];

  // If this bean has @Value fields, add config token as last dependency
  const beanValueFields = bean.metadata.valueFields as
    | Array<{ fieldName: string; key: string; default?: string }>
    | undefined;
  if (hasValueFields && beanValueFields && beanValueFields.length > 0) {
    allDeps.push({
      token: '__Goodie_Config',
      optional: false,
      collection: false,
    });
  }

  // If this bean has intercepted methods, add interceptor class tokens as deps
  const interceptorDeps = cachedInterceptorDeps.get(bean) ?? new Map();
  for (const ref of interceptorDeps.values()) {
    const tokenRef: TokenRef = {
      kind: 'class',
      className: ref.className,
      importPath: ref.importPath,
    };
    allDeps.push({
      token: resolveTokenRef(tokenRef),
      optional: false,
      collection: false,
    });
  }

  if (allDeps.length === 0) return '[]';

  const items = allDeps.map((d) => {
    const parts = [
      `token: ${d.token}`,
      `optional: ${d.optional}`,
      `collection: ${d.collection}`,
    ];
    return `{ ${parts.join(', ')} }`;
  });
  return `[${items.join(', ')}]`;
}

/** Generate the factory function code for a bean. */
function factoryToCode(
  bean: IRBeanDefinition,
  cachedInterceptorDeps: Map<IRBeanDefinition, Map<string, InterceptorRefMeta>>,
): string {
  if (bean.factoryKind === 'provides') {
    return providesFactoryToCode(bean);
  }

  return constructorFactoryToCode(bean, cachedInterceptorDeps);
}

function constructorFactoryToCode(
  bean: IRBeanDefinition,
  cachedInterceptorDeps: Map<IRBeanDefinition, Map<string, InterceptorRefMeta>>,
): string {
  const className =
    bean.tokenRef.kind === 'class'
      ? bean.tokenRef.className
      : bean.tokenRef.tokenName;

  const beanValueFields = bean.metadata.valueFields as
    | Array<{ fieldName: string; key: string; default?: string }>
    | undefined;
  const hasValues = beanValueFields && beanValueFields.length > 0;

  const interceptedMethods = bean.metadata.interceptedMethods as
    | InterceptedMethodMeta[]
    | undefined;
  const hasInterception =
    interceptedMethods !== undefined && interceptedMethods.length > 0;
  const interceptorDeps = cachedInterceptorDeps.get(bean) ?? new Map();

  const ctorParams = bean.constructorDeps.map((_, i) => `dep${i}`);
  const allParams = [...ctorParams];
  const fieldParams = bean.fieldDeps.map((_, i) => `field${i}`);
  allParams.push(...fieldParams);
  if (hasValues) {
    allParams.push('__config');
  }

  // Add interceptor params after config and build key -> param name map
  const interceptorParamMap = new Map<string, string>();
  if (hasInterception) {
    let i = 0;
    for (const [key] of interceptorDeps) {
      const paramName = `__interceptor${i}`;
      interceptorParamMap.set(key, paramName);
      allParams.push(paramName);
      i++;
    }
  }

  const needsBody = bean.fieldDeps.length > 0 || hasValues || hasInterception;

  if (allParams.length === 0 && !needsBody) {
    return `() => new ${className}()`;
  }

  const paramList = allParams.map((p) => `${p}: any`).join(', ');
  const ctorArgs = ctorParams.join(', ');

  if (!needsBody) {
    return `(${paramList}) => new ${className}(${ctorArgs})`;
  }

  // Constructor + field injection + value injection + interception
  const bodyLines: string[] = [];

  // Field assignments
  for (let i = 0; i < bean.fieldDeps.length; i++) {
    bodyLines.push(`    instance.${bean.fieldDeps[i].fieldName} = field${i}`);
  }

  // Value assignments
  if (hasValues) {
    for (const vf of beanValueFields) {
      const safeKey = escapeStringLiteral(vf.key);
      if (vf.default !== undefined) {
        bodyLines.push(
          `    instance.${vf.fieldName} = __config['${safeKey}'] ?? ${vf.default}`,
        );
      } else {
        bodyLines.push(`    instance.${vf.fieldName} = __config['${safeKey}']`);
      }
    }
  }

  // Interceptor wrapping
  if (hasInterception) {
    for (const desc of interceptedMethods) {
      const interceptorArgs = desc.interceptors.map((ref) => {
        const key = `${ref.importPath}:${ref.className}`;
        const paramName = interceptorParamMap.get(key)!;
        if (ref.adviceType === 'before') {
          return `wrapBeforeAdvice(${paramName})`;
        }
        if (ref.adviceType === 'after') {
          return `wrapAfterAdvice(${paramName})`;
        }
        return paramName;
      });

      // Build per-interceptor metadata array if any interceptor has metadata
      const hasMetadata = desc.interceptors.some((ref) => ref.metadata);
      let metadataArg = '';
      if (hasMetadata) {
        const metadataItems = desc.interceptors.map((ref) =>
          ref.metadata ? JSON.stringify(ref.metadata) : 'undefined',
        );
        metadataArg = `, [${metadataItems.join(', ')}]`;
      }

      const safeMethodName = escapeStringLiteral(desc.methodName);
      bodyLines.push(
        `    instance.${desc.methodName} = buildInterceptorChain([${interceptorArgs.join(', ')}], instance, '${escapeStringLiteral(className)}', '${safeMethodName}', instance.${desc.methodName}.bind(instance)${metadataArg})`,
      );
    }
  }

  const body = bodyLines.join('\n');
  return `(${paramList}) => {
    const instance = new ${className}(${ctorArgs})
${body}
    return instance
  }`;
}

function providesFactoryToCode(bean: IRBeanDefinition): string {
  if (!bean.providesSource)
    return '() => { throw new Error("missing provides source") }';

  const { moduleTokenRef, methodName } = bean.providesSource;

  // First dep is always the module instance
  const params = bean.constructorDeps.map((_, i) => `dep${i}: any`);
  const args = bean.constructorDeps.slice(1).map((_, i) => `dep${i + 1}`);

  const paramList = params.join(', ');
  const argList = args.join(', ');

  return `(${paramList}) => (dep0 as ${moduleTokenRef.className}).${methodName}(${argList})`;
}

function metadataToCode(metadata: Record<string, unknown>): string {
  const entries = Object.entries(metadata);
  if (entries.length === 0) return '{}';

  const items = entries.map(([k, v]) => `${k}: ${JSON.stringify(v)}`);
  return `{ ${items.join(', ')} }`;
}

/** Compute a relative import path from the output dir to the target file, with .js extension. */
function computeRelativeImport(
  outputDir: string,
  absolutePath: string,
): string {
  // Handle node_modules paths → extract bare package specifier
  if (absolutePath.includes('node_modules')) {
    return extractPackageName(absolutePath);
  }

  // Bare module specifiers (e.g. '@goodie-ts/logging', 'lodash') — return as-is
  if (!path.isAbsolute(absolutePath)) {
    return absolutePath;
  }

  let relative = path.relative(outputDir, absolutePath);

  // Replace .ts extension with .js
  relative = relative.replace(/\.tsx?$/, '.js');

  // Ensure it starts with ./
  if (!relative.startsWith('.')) {
    relative = `./${relative}`;
  }

  return relative;
}

/**
 * Extract a bare package name from a node_modules path.
 * E.g. '/project/node_modules/pg/lib/index.d.ts' → 'pg'
 *      '/project/node_modules/@types/pg/index.d.ts' → 'pg'
 *      '/project/node_modules/@scope/pkg/lib/index.d.ts' → '@scope/pkg'
 */
function extractPackageName(absolutePath: string): string {
  const segments = absolutePath.split('/node_modules/');
  const afterNodeModules = segments[segments.length - 1];
  const parts = afterNodeModules.split('/');

  let packageName: string;
  if (parts[0].startsWith('@')) {
    // Scoped package: @scope/name
    packageName = `${parts[0]}/${parts[1]}`;
  } else {
    packageName = parts[0];
  }

  // Strip @types/ prefix (e.g. @types/pg → pg)
  if (packageName.startsWith('@types/')) {
    packageName = packageName.slice('@types/'.length);
  }

  return packageName;
}

/**
 * Escape characters that could break out of a single-quoted string literal.
 * Prevents code injection via @Value keys.
 */
function escapeStringLiteral(value: string): string {
  return value
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r');
}

// ── EmbeddedServer bean generation ──

/**
 * Generate the EmbeddedServer bean definition lines (to be inserted inside the definitions array).
 * The factory creates a Hono app, wires all controller routes, and returns new EmbeddedServer(app).
 */
function generateEmbeddedServerBeanDef(
  controllers: IRControllerDefinition[],
): string[] {
  const lines: string[] = [];
  const ctrlVarNames = buildControllerVarNames(controllers);

  // Dependencies: one per controller
  const deps = controllers.map(
    (ctrl) =>
      `{ token: ${ctrl.classTokenRef.className}, optional: false, collection: false }`,
  );

  // Factory params: collision-safe controller variable names
  const params = controllers.map((ctrl) => {
    const varName = ctrlVarNames.get(controllerKey(ctrl))!;
    return `${varName}: any`;
  });

  lines.push('  {');
  lines.push('    token: EmbeddedServer,');
  lines.push("    scope: 'singleton',");
  lines.push(`    dependencies: [${deps.join(', ')}],`);
  lines.push(`    factory: (${params.join(', ')}) => {`);
  lines.push('      const __honoApp = new Hono()');

  for (const ctrl of controllers) {
    const varName = ctrlVarNames.get(controllerKey(ctrl))!;
    for (const route of ctrl.routes) {
      const fullPath = escapeStringLiteral(
        joinPaths(ctrl.basePath, route.path),
      );
      const validationMiddleware = generateValidationMiddleware(
        route.validation,
      );

      if (validationMiddleware.length > 0) {
        // Route with validation middleware
        lines.push(`      __honoApp.${route.httpMethod}('${fullPath}',`);
        for (const mw of validationMiddleware) {
          lines.push(`        ${mw},`);
        }
        lines.push('        async (c) => {');
      } else {
        lines.push(
          `      __honoApp.${route.httpMethod}('${fullPath}', async (c) => {`,
        );
      }
      lines.push(
        `        const result = await ${varName}.${route.methodName}(c)`,
      );
      lines.push('        if (result instanceof Response) return result');
      lines.push(
        '        if (result === undefined || result === null) return c.body(null, 204)',
      );
      lines.push('        return c.json(result)');
      lines.push('      })');
    }
  }

  lines.push('      return new EmbeddedServer(__honoApp)');
  lines.push('    },');
  lines.push('    eager: false,');
  lines.push('    metadata: {},');
  lines.push('  },');

  return lines;
}

/**
 * Build a Map<"className:importPath", uniqueVarName> with collision detection.
 * When two controllers produce the same camelCase name, append _2, _3, etc.
 * Uses composite key to handle same-named controllers from different files.
 */
function buildControllerVarNames(
  controllers: IRControllerDefinition[],
): Map<string, string> {
  const result = new Map<string, string>();
  const varNameCounts = new Map<string, number>();

  for (const ctrl of controllers) {
    const key = controllerKey(ctrl);
    const className = ctrl.classTokenRef.className;
    const baseVarName = className.charAt(0).toLowerCase() + className.slice(1);
    const count = varNameCounts.get(baseVarName) ?? 0;

    if (count === 0) {
      result.set(key, baseVarName);
    } else {
      result.set(key, `${baseVarName}_${count + 1}`);
    }
    varNameCounts.set(baseVarName, count + 1);
  }

  return result;
}

/** Stable key for a controller to avoid same-name collisions across files. */
function controllerKey(ctrl: IRControllerDefinition): string {
  return `${ctrl.classTokenRef.className}:${ctrl.classTokenRef.importPath}`;
}

/** Join a base path and a route path, normalizing slashes. */
function joinPaths(basePath: string, routePath: string): string {
  // Normalize: remove trailing slash from base, ensure leading slash on route
  const base = basePath.endsWith('/') ? basePath.slice(0, -1) : basePath;
  const route = routePath.startsWith('/') ? routePath : `/${routePath}`;

  // Special case: if route is just '/', return the base
  if (route === '/') return base || '/';

  return `${base}${route}`;
}

/** Generate zValidator() middleware calls for a route's validation targets. */
function generateValidationMiddleware(
  validation: IRRouteValidation[] | undefined,
): string[] {
  if (!validation || validation.length === 0) return [];
  return validation.map(
    (v) =>
      `zValidator('${v.target}', ${v.schemaRef}, (result, c) => { if (!result.success) return c.json({ error: 'Validation failed', issues: result.error.issues.map((i: any) => ({ path: i.path, message: i.message })) }, 400) })`,
  );
}

/**
 * Collect unique schema imports from validated routes.
 * Returns a Map from schema variable name to relative import path.
 */
function collectSchemaImports(
  controllers: IRControllerDefinition[],
  outputDir: string,
): Map<string, string> {
  const imports = new Map<string, string>();
  for (const ctrl of controllers) {
    for (const route of ctrl.routes) {
      if (!route.validation) continue;
      for (const v of route.validation) {
        if (!imports.has(v.schemaRef)) {
          imports.set(
            v.schemaRef,
            computeRelativeImport(outputDir, v.importPath),
          );
        }
      }
    }
  }
  return imports;
}
