import type { ApplicationContext } from '@goodie-ts/core';

import type { ExceptionHandler } from './exception-handler.js';

/**
 * Function type for compile-time generated route wiring.
 *
 * Generated by adapter transformer plugins (e.g. hono) via `emitFiles`.
 * Registers all controller routes on the provided router with pre-compiled
 * param binding, coercion, and error handling.
 *
 * The router type is generic — each adapter (Hono, Express, etc.) provides
 * its own concrete type.
 */
export type GeneratedRouteWirer<TRouter = unknown> = (
  ctx: ApplicationContext,
  router: TRouter,
  exceptionHandlers: ExceptionHandler[],
) => void;

let _generatedRouteWirer: GeneratedRouteWirer | undefined;

/**
 * Register a compile-time generated route wiring function.
 *
 * Called as a side effect from the generated `routes.ts` file.
 * When registered, adapter bootstraps use it instead of
 * runtime metadata interpretation.
 */
export function registerGeneratedRoutes<TRouter>(
  wirer: GeneratedRouteWirer<TRouter>,
): void {
  _generatedRouteWirer = wirer as GeneratedRouteWirer;
}

/**
 * Retrieve the registered compile-time route wirer, if any.
 *
 * Used by adapter packages (e.g. `@goodie-ts/hono`) to check whether
 * generated routes are available before falling back to runtime wiring.
 */
export function getGeneratedRouteWirer<TRouter>():
  | GeneratedRouteWirer<TRouter>
  | undefined {
  return _generatedRouteWirer as GeneratedRouteWirer<TRouter> | undefined;
}

/**
 * Clear the registered route wirer. For test isolation.
 */
export function resetGeneratedRoutes(): void {
  _generatedRouteWirer = undefined;
}
